name: Terraform CI-CD

on:
  push:
    branches:
      - feature/github-pipeline
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # =====================================================
  # TERRAFORM PLAN - Feature Branch / PR / Main
  # =====================================================

  terraform-plan:
    name: Terraform Init Validate Plan
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4


      # Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3


      # Terraform Format Check
      - name: Terraform Format Check
        working-directory: parent-module
        run: terraform fmt -check -recursive


      # Terraform Init
      - name: Terraform Init
        working-directory: parent-module
        run: terraform init


      # Terraform Validate
      - name: Terraform Validate
        working-directory: parent-module
        run: terraform validate


      # Terraform Plan
      - name: Terraform Plan
        working-directory: parent-module
        run: terraform plan -var-file="terraform.tfvars"


  # =====================================================
  # TERRAFORM APPLY - MAIN ONLY
  # =====================================================

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after merge/push to main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4


      # Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3


      # Terraform Init
      - name: Terraform Init
        working-directory: parent-module
        run: terraform init


      # Terraform Apply
      - name: Terraform Apply
        working-directory: parent-module
        run: terraform apply -auto-approve -var-file="terraform.tfvars"